/***************************************************************\
 *     The skeleton of this class is generated by an automatic *
 * code generator for NC product. It is based on Velocity.     *
\***************************************************************/
package nc.vo.ta.leavebalance;
	
import nc.vo.pub.SuperVO;
import nc.vo.pub.lang.UFDouble;
import nc.vo.pub.lang.UFLiteralDate;
import nc.vo.ta.psndoc.TBMPsndocVO;
import nc.vo.ta.timeitem.LeaveTypeCopyVO;

/**
 * <b> 在此处简要描述此类的功能 </b>
 * <p>
 *     在此处添加此类的描述信息
 * </p>
 * 创建日期:2010-09-28 11:28:25
 * @author 
 * @version NCPrj ??
 */
@SuppressWarnings("serial")
public class LeaveBalanceVO extends SuperVO {
	private java.lang.String pk_leavebalance;
	private java.lang.String pk_group;
	private java.lang.String pk_org;
	private java.lang.String pk_psndoc;
	private String pk_psnorg;
	private java.lang.String pk_psnjob;	//虚字段，数据库中没有
	private String pk_tbm_psndoc;//虚字段，数据库中没有
	private java.lang.String pk_timeitem;
	private java.lang.String pk_timeitemcopy;
	private nc.vo.pub.lang.UFDouble lastdayorhour;
	private nc.vo.pub.lang.UFDouble curdayorhour;
	private nc.vo.pub.lang.UFDouble realdayorhour;
	private nc.vo.pub.lang.UFDouble yidayorhour;
	private nc.vo.pub.lang.UFDouble restdayorhour;
	private nc.vo.pub.lang.UFDouble freezedayorhour;
	private nc.vo.pub.lang.UFDateTime calculatetime;
	private UFLiteralDate settlementdate;
	private java.lang.String curyear;
	private java.lang.String curmonth;
	private Integer leaveindex;
	private nc.vo.pub.lang.UFBoolean issettlement;
	private nc.vo.pub.lang.UFBoolean isuse;
	private nc.vo.pub.lang.UFBoolean isabnormalset;//是否非正常结算。对于中途离职的人员，可以提前结算，结算后要打上非正常计算标记
	private UFLiteralDate hirebegindate;//按入职日结算的类别此字段有效，表示此入职年度的开始日期
	private UFLiteralDate hireenddate;//按入职日结算的类别此字段有效，表示此入职年度的结束日期
	private UFLiteralDate periodbegindate;//虚字段，数据库不存。期间的开始日期，对于按年结算的类别，是考勤年度的第一天；对于按期间结算的，是期间的第一天；对于按入职日计算的，等于hirebegindate
	private UFLiteralDate periodenddate;//虚字段，数据库不存。期间的结束日期，对于按年结算的类别，是考勤年度的最后一天；对于按期间结算的，是期间的最后一天；对于按入职日计算的，等于hireenddate
	private UFLiteralDate periodextendenddate;//虚字段，数据库不存。期间的结束日期加上有效期延长天数后的日期。若有效期延长天数为0，则等于periodenddate
	private Integer settlementmethod;//结算方式，过期作废，转下期，转工资，在结算时记录
	private java.lang.Integer dr = 0;
	private nc.vo.pub.lang.UFDateTime ts;
	
	private java.lang.String pk_org_v;//虚字段 人员所属期间最新组织版本
	private java.lang.String  pk_dept_v;//虚字段  人员所属期间最新部门版本
	
	private int leavesetperiod;//虚字段，结算周期，分为年/入职日/期间
	private UFDouble translatein;//转入时长
	private UFDouble translateout;//转出时长
	private nc.vo.pub.lang.UFBoolean transflag;//转移标识
	private UFDouble changelength;//调整时长
	private java.lang.String salaryyear;
	private java.lang.String salarymonth;
	
	// HR本地化：假期计算添加备注字段 Ethan Wu 2019-02-15 start
	private java.lang.String remarks;
	// HR本地化：假期计算添加备注字段 Ethan Wu 2019-02-15 end
	
	public static final String PK_LEAVEBALANCE = "pk_leavebalance";
	public static final String PK_TBM_PSNDOC = "pk_tbm_psndoc";
	public static final String PK_GROUP = "pk_group";
	public static final String PK_ORG = "pk_org";
	public static final String PK_ORG_V = "pk_org_v";
	public static final String PK_DEPT_V = "pk_dept_v";
	public static final String PK_PSNDOC = "pk_psndoc";
	public static final String PK_PSNORG = "pk_psnorg";
	public static final String PK_PSNJOB = "pk_psnjob";
	public static final String PK_TIMEITEM = "pk_timeitem";
	public static final String PK_TIMEITEMCOPY = "pk_timeitemcopy";
	public static final String LASTDAYORHOUR = "lastdayorhour";
	public static final String CURDAYORHOUR = "curdayorhour";
	public static final String REALDAYORHOUR = "realdayorhour";
	public static final String YIDAYORHOUR = "yidayorhour";
	public static final String RESTDAYORHOUR = "restdayorhour";
	public static final String FREEZEDAYORHOUR = "freezedayorhour";
	public static final String USEFULRESTDAYORHOUR = "usefulrestdayorhour";
	public static final String CALCULATETIME = "calculatetime";
	public static final String SETTLEMENTDATE = "settlementdate";
	public static final String CURYEAR = "curyear";
	public static final String CURMONTH = "curmonth";
	public static final String LEAVEINDEX = "leaveindex";
	public static final String ISSETTLEMENT = "issettlement";
	public static final String ISUSE = "isuse";
	public static final String ISABNORMALSET = "isabnormalset";
	public static final String HIREBEGINDATE = "hirebegindate";
	public static final String SETTLEMENTMETHOD = "settlementmethod";
	public static final String HIREENDDATE = "hireenddate";
	public static final String TRANSLATEIN = "translatein";
	public static final String TRANSLATEOUT = "translateout";
	public static final String TRANSFLAG = "transflag";
	public static final String CHANGELENGTH = "changelength";
	public static final String SALARYYEAR = "salaryyear";
	public static final String SALARYMONTH = "salarymonth";
	
	// HR本地化：假期计算添加备注字段 Ethan Wu 2019-02-15 start
	public static final String REMARKS = "remarks";
	// HR本地化：假期计算添加备注字段 Ethan Wu 2019-02-15 end
	
	public static final String TIMETOLEAVETYPE = "1002Z710000000021ZM1";
			
	/**
	 * 属性pk_leavebalance的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getPk_leavebalance () {
		return pk_leavebalance;
	}   
	/**
	 * 属性pk_leavebalance的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newPk_leavebalance java.lang.String
	 */
	public void setPk_leavebalance (java.lang.String newPk_leavebalance ) {
	 	this.pk_leavebalance = newPk_leavebalance;
	} 	  
	/**
	 * 属性pk_group的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getPk_group () {
		return pk_group;
	}   
	/**
	 * 属性pk_group的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newPk_group java.lang.String
	 */
	public void setPk_group (java.lang.String newPk_group ) {
	 	this.pk_group = newPk_group;
	} 	  
	/**
	 * 属性pk_org的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getPk_org () {
		return pk_org;
	}   
	/**
	 * 属性pk_org的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newPk_org java.lang.String
	 */
	public void setPk_org (java.lang.String newPk_org ) {
	 	this.pk_org = newPk_org;
	} 	  
	/**
	 * 属性pk_psndoc的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getPk_psndoc () {
		return pk_psndoc;
	}   
	/**
	 * 属性pk_psndoc的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newPk_psndoc java.lang.String
	 */
	public void setPk_psndoc (java.lang.String newPk_psndoc ) {
	 	this.pk_psndoc = newPk_psndoc;
	} 	  
	/**
	 * 属性pk_timeitem的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getPk_timeitem () {
		return pk_timeitem;
	}   
	/**
	 * 属性pk_timeitem的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newPk_timeitem java.lang.String
	 */
	public void setPk_timeitem (java.lang.String newPk_timeitem ) {
	 	this.pk_timeitem = newPk_timeitem;
	} 	  
	/**
	 * 属性lastdayorhour的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getLastdayorhour () {
		return lastdayorhour;
	}   
	/**
	 * 属性lastdayorhour的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newLastdayorhour nc.vo.pub.lang.UFDouble
	 */
	public void setLastdayorhour (nc.vo.pub.lang.UFDouble newLastdayorhour ) {
	 	this.lastdayorhour = newLastdayorhour;
	} 	  
	/**
	 * 属性curdayorhour的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getCurdayorhour () {
		return curdayorhour;
	}   
	/**
	 * 属性curdayorhour的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newCurdayorhour nc.vo.pub.lang.UFDouble
	 */
	public void setCurdayorhour (nc.vo.pub.lang.UFDouble newCurdayorhour ) {
	 	this.curdayorhour = newCurdayorhour;
	} 	  
	/**
	 * 属性realdayorhour的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getRealdayorhour () {
		return realdayorhour;
	}   
	/**
	 * 属性realdayorhour的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newRealdayorhour nc.vo.pub.lang.UFDouble
	 */
	public void setRealdayorhour (nc.vo.pub.lang.UFDouble newRealdayorhour ) {
	 	this.realdayorhour = newRealdayorhour;
	} 	  
	/**
	 * 属性yidayorhour的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getYidayorhour () {
		return yidayorhour;
	}   
	/**
	 * 属性yidayorhour的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newYidayorhour nc.vo.pub.lang.UFDouble
	 */
	public void setYidayorhour (nc.vo.pub.lang.UFDouble newYidayorhour ) {
	 	this.yidayorhour = newYidayorhour;
	} 	  
	/**
	 * 属性restdayorhour的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDouble
	 */
	public nc.vo.pub.lang.UFDouble getRestdayorhour () {
		return restdayorhour;
	}
	
	public void minusRestdayorhour(double toMinusLen){
		if(toMinusLen==0)
			return;
		if(getRestdayorhour()==null){
			setRestdayorhour(new UFDouble(0-toMinusLen));
			return;
		}
		setRestdayorhour(getRestdayorhour().sub(toMinusLen));
	}
	
	public void plusFreezedayorhour(double toPlusLen){
		if(toPlusLen==0)
			return;
		if(getFreezedayorhour()==null){
			setFreezedayorhour(new UFDouble(toPlusLen));
			return;
		}
		setFreezedayorhour(getFreezedayorhour().add(toPlusLen));
	}
	
	public double getRestDayOrHourValue(){
		return restdayorhour==null?0:restdayorhour.doubleValue();
	}
	
	/**
	 * 可用的结余时长，由结余时长减去冻结时长
	 * @return
	 */
	public double getUsefulRestDayOrHour(){
		return getRestDayOrHourValue()-(getFreezedayorhour()==null?0.0:getFreezedayorhour().doubleValue());
	}
	
	/**
	 * 可用的结余时长，由结余时长减去冻结时长
	 * @return
	 */
	public UFDouble getUsefulrestdayorhour(){
		return new UFDouble(getUsefulRestDayOrHour());
	}
	/**
	 * 属性restdayorhour的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newRestdayorhour nc.vo.pub.lang.UFDouble
	 */
	public void setRestdayorhour (nc.vo.pub.lang.UFDouble newRestdayorhour ) {
	 	this.restdayorhour = newRestdayorhour;
	} 	  
	public java.lang.String getPk_timeitemcopy() {
		return pk_timeitemcopy;
	}
	public void setPk_timeitemcopy(java.lang.String pk_timeitemcopy) {
		this.pk_timeitemcopy = pk_timeitemcopy;
	}
	/**
	 * 属性calculatetime的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getCalculatetime () {
		return calculatetime;
	}   
	/**
	 * 属性calculatetime的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newCalculatetime nc.vo.pub.lang.UFDateTime
	 */
	public void setCalculatetime (nc.vo.pub.lang.UFDateTime newCalculatetime ) {
	 	this.calculatetime = newCalculatetime;
	} 	  
	/**
	 * 属性curyear的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getCuryear () {
		return curyear;
	}   
	/**
	 * 属性curyear的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newCuryear java.lang.String
	 */
	public void setCuryear (java.lang.String newCuryear ) {
	 	this.curyear = newCuryear;
	} 	  
	/**
	 * 属性curmonth的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getCurmonth () {
		return curmonth;
	}   
	/**
	 * 属性curmonth的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newCurmonth java.lang.String
	 */
	public void setCurmonth (java.lang.String newCurmonth ) {
	 	this.curmonth = newCurmonth;
	} 	  
	/**
	 * 属性isseal的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIssettlement () {
		return issettlement;
	}   
	/**
	 * 属性isseal的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newIsseal nc.vo.pub.lang.UFBoolean
	 */
	public void setIssettlement (nc.vo.pub.lang.UFBoolean issettlement ) {
	 	this.issettlement = issettlement;
	} 	  
	/**
	 * 属性isuse的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFBoolean
	 */
	public nc.vo.pub.lang.UFBoolean getIsuse () {
		return isuse;
	}   
	/**
	 * 属性isuse的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newIsuse nc.vo.pub.lang.UFBoolean
	 */
	public void setIsuse (nc.vo.pub.lang.UFBoolean newIsuse ) {
	 	this.isuse = newIsuse;
	} 	  
	/**
	 * 属性dr的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.Integer
	 */
	public java.lang.Integer getDr () {
		return dr;
	}   
	/**
	 * 属性dr的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newDr java.lang.Integer
	 */
	public void setDr (java.lang.Integer newDr ) {
	 	this.dr = newDr;
	} 	  
	/**
	 * 属性ts的Getter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @return nc.vo.pub.lang.UFDateTime
	 */
	public nc.vo.pub.lang.UFDateTime getTs () {
		return ts;
	}   
	/**
	 * 属性ts的Setter方法.
	 * 创建日期:2010-09-28 11:28:25
	 * @param newTs nc.vo.pub.lang.UFDateTime
	 */
	public void setTs (nc.vo.pub.lang.UFDateTime newTs ) {
	 	this.ts = newTs;
	} 	  
 
	/**
	  * <p>取得父VO主键字段.
	  * <p>
	  * 创建日期:2010-09-28 11:28:25
	  * @return java.lang.String
	  */
	public java.lang.String getParentPKFieldName() {
	    return null;
	}   
    
	/**
	  * <p>取得表主键.
	  * <p>
	  * 创建日期:2010-09-28 11:28:25
	  * @return java.lang.String
	  */
	public java.lang.String getPKFieldName() {
	  return "pk_leavebalance";
	}
    
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public java.lang.String getTableName() {
		return "tbm_leavebalance";
	}    
	
	/**
	 * <p>返回表名称.
	 * <p>
	 * 创建日期:2010-09-28 11:28:25
	 * @return java.lang.String
	 */
	public static java.lang.String getDefaultTableName() {
		return "tbm_leavebalance";
	}    
    
    /**
	  * 按照默认方式创建构造子.
	  *
	  * 创建日期:2010-09-28 11:28:25
	  */
     public LeaveBalanceVO() {
		super();	
	}
	public UFLiteralDate getSettlementdate() {
		return settlementdate;
	}
	public void setSettlementdate(UFLiteralDate settlementdate) {
		this.settlementdate = settlementdate;
	}
	public java.lang.String getPk_psnjob() {
		return pk_psnjob;
	}
	public void setPk_psnjob(java.lang.String pk_psnjob) {
		this.pk_psnjob = pk_psnjob;
	}
	public nc.vo.pub.lang.UFDouble getFreezedayorhour() {
		return freezedayorhour;
	}
	public void setFreezedayorhour(nc.vo.pub.lang.UFDouble freezedayorhour) {
		this.freezedayorhour = freezedayorhour;
	}    
	
	public void sync(LeaveBalanceVO anotherVO){
		this.pk_leavebalance=anotherVO.getPk_leavebalance();
		this.curdayorhour=anotherVO.getCurdayorhour();
		this.realdayorhour=anotherVO.getRealdayorhour();
		this.freezedayorhour=anotherVO.getFreezedayorhour();
		this.yidayorhour=anotherVO.getYidayorhour();
		this.restdayorhour=anotherVO.getRestdayorhour();
		this.lastdayorhour=anotherVO.getLastdayorhour();
		this.issettlement=anotherVO.getIssettlement();
		this.isuse=anotherVO.getIsuse();
		this.isabnormalset=anotherVO.getIsabnormalset();
		this.settlementdate=anotherVO.getSettlementdate();
		this.calculatetime=anotherVO.getCalculatetime();
		this.settlementmethod=anotherVO.getSettlementmethod();
		this.ts=anotherVO.getTs();
	}
	public nc.vo.pub.lang.UFBoolean getIsabnormalset() {
		return isabnormalset;
	}
	public void setIsabnormalset(nc.vo.pub.lang.UFBoolean isabnormalset) {
		this.isabnormalset = isabnormalset;
	}
	public UFLiteralDate getHirebegindate() {
		return hirebegindate;
	}
	public void setHirebegindate(UFLiteralDate hirebegindate) {
		this.hirebegindate = hirebegindate;
	}
	public UFLiteralDate getHireenddate() {
		return hireenddate;
	}
	public void setHireenddate(UFLiteralDate hireenddate) {
		this.hireenddate = hireenddate;
	}
	public String getPk_psnorg() {
		return pk_psnorg;
	}
	public void setPk_psnorg(String pkPsnorg) {
		pk_psnorg = pkPsnorg;
	}
	
	public boolean isSettlement(){
		return issettlement!=null&&issettlement.booleanValue();
	}
	public boolean isUse(){
		return isuse!=null&&isuse.booleanValue();
	}
	public Integer getLeaveindex() {
		return leaveindex;
	}
	public void setLeaveindex(Integer leaveindex) {
		this.leaveindex = leaveindex;
	}
	public boolean canCalculate(){
		return !isSettlement()&&!isUse();
	}
	public Integer getSettlementmethod() {
		return settlementmethod;
	}
	public void setSettlementmethod(Integer settlementmethod) {
		this.settlementmethod = settlementmethod;
	}
	
	public TBMPsndocVO toTBMPsndocVO(){
		TBMPsndocVO vo = new TBMPsndocVO();
		vo.setPrimaryKey(pk_tbm_psndoc);
		vo.setPk_psndoc(pk_psndoc);
		vo.setPk_psnjob(pk_psnjob);
		vo.setPk_group(pk_group);
		vo.setPk_org(pk_org);
		return vo;
	}
	public String getPk_tbm_psndoc() {
		return pk_tbm_psndoc;
	}
	public void setPk_tbm_psndoc(String pkTbmPsndoc) {
		pk_tbm_psndoc = pkTbmPsndoc;
	}
	public java.lang.String getPk_org_v() {
		return pk_org_v;
	}
	public void setPk_org_v(java.lang.String pkOrgV) {
		pk_org_v = pkOrgV;
	}
	public java.lang.String getPk_dept_v() {
		return pk_dept_v;
	}
	public void setPk_dept_v(java.lang.String pkDeptV) {
		pk_dept_v = pkDeptV;
	}
	public UFLiteralDate getPeriodbegindate() {
		return periodbegindate;
	}
	public void setPeriodbegindate(UFLiteralDate periodbegindate) {
		this.periodbegindate = periodbegindate;
	}
	public UFLiteralDate getPeriodenddate() {
		return periodenddate;
	}
	public void setPeriodenddate(UFLiteralDate periodenddate) {
		this.periodenddate = periodenddate;
	}
	public UFLiteralDate getPeriodextendenddate() {
		return periodextendenddate;
	}
	public void setPeriodextendenddate(UFLiteralDate periodextendenddate) {
		this.periodextendenddate = periodextendenddate;
	}
	public int getLeavesetperiod() {
		return leavesetperiod;
	}
	public void setLeavesetperiod(int leavesetperiod) {
		this.leavesetperiod = leavesetperiod;
	}
	
	public boolean isYearDateSetPeriod(){
		return leavesetperiod!=LeaveTypeCopyVO.LEAVESETPERIOD_MONTH;
	}
	
	public String getPeriodStr(){
		return isYearDateSetPeriod()?curyear:(curyear+curmonth);
	}
	public UFDouble getTranslatein() {
		return translatein;
	}
	public void setTranslatein(UFDouble translatein) {
		this.translatein = translatein;
	}
	public UFDouble getTranslateout() {
		return translateout;
	}
	public void setTranslateout(UFDouble translateout) {
		this.translateout = translateout;
	}
	public nc.vo.pub.lang.UFBoolean getTransflag() {
		return transflag;
	}
	public void setTransflag(nc.vo.pub.lang.UFBoolean transflag) {
		this.transflag = transflag;
	}
	public boolean getTransFlagValue(){
		return transflag!=null && transflag.booleanValue();
	}
	
	public void setChangelength(UFDouble changelength) {
		this.changelength = changelength;
	}
	public nc.vo.pub.lang.UFDouble getChangelength() {
		return changelength;
	}
	public java.lang.String getSalaryyear() {
		return salaryyear;
	}
	public void setSalaryyear(java.lang.String salaryyear) {
		this.salaryyear = salaryyear;
	}
	public java.lang.String getSalarymonth() {
		return salarymonth;
	}
	public void setSalarymonth(java.lang.String salarymonth) {
		this.salarymonth = salarymonth;
	}
	
	// HR本地化：假期计算添加备注字段 Ethan Wu 2019-02-15 start
	public java.lang.String getRemarks() {
		return remarks;
	}
	public void setRemarks(java.lang.String remarks) {
		this.remarks = remarks;
	}
	// HR本地化：假期计算添加备注字段 Ethan Wu 2019-02-15 end
} 


